[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",   
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.gd",
  "php82Extensions.dom",
  "php82Extensions.session",
  "php82Extensions.simplexml",
  "php82Extensions.filter"
]

[phases.build]
cmds = [
  # Crear los directorios necesarios para CSS/JS/PHP
  "mkdir -p web/sites/default/files/css web/sites/default/files/js web/sites/default/files/php",
  
  # Dar permisos
  "chmod -R 777 web/sites/default/files",
  
  # Instalar dependencias
  "composer install --no-dev --optimize-autoloader",
  
  # Reconstruir caché y generar agregados
  "./vendor/bin/drush cr",
  
  # Importar configuración si es necesario
  #"./vendor/bin/drush cim -y" 
]

[start]
cmd = "./scripts/migrate-files.sh",
cmd = "php -S 0.0.0.0:$PORT -t web"
