[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",   # 👈 agrega composer aquí
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.gd",
  "php82Extensions.dom",
  "php82Extensions.session",
  "php82Extensions.simplexml",
  "php82Extensions.filter"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t web"
