[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",   
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.gd",
  "php82Extensions.dom",
  "php82Extensions.session",
  "php82Extensions.simplexml",
  "php82Extensions.filter"
]

[phases.build]
cmds = [
  # Crear los directorios necesarios para CSS/JS/PHP
  "mkdir -p web/sites/default/files/css web/sites/default/files/js web/sites/default/files/php",
  
  # Dar permisos para evitar errores de escritura
  "chmod -R 777 web/sites/default/files",
  #"chmod -R +x ./scripts",

  # Instalar dependencias
  "composer install --no-dev --optimize-autoloader",

  "ls -la",

  # Importar files system
  #"./scripts/migrate-files.sh",

  # Descargar y descomprimir el tar.gz
  "curl -L $FILES_TAR_URL -o /tmp/files.tar.gz",
  "tar -xzf /tmp/files.tar.gz -C web/sites/default/files",
  "rm /tmp/files.tar.gz",

  # Reconstruir caché (opcional pero recomendado en build)
  "./vendor/bin/drush cr"
]

[start]
# Aquí es donde realmente migramos los archivos en cada despliegue
cmd = "php -S 0.0.0.0:$PORT -t web"
