[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",   
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.gd",
  "php82Extensions.dom",
  "php82Extensions.session",
  "php82Extensions.simplexml",
  "php82Extensions.filter"
]

[phases.build]
cmds = [
  # Eliminar contenido previo
  "rm -rf web/sites/default/files",

  # Asegurarse de que la carpeta exista
  "mkdir -p web/sites/default",

  # Dar permisos
  "chmod -R 777 web/sites/default/",

  # Descargar y descomprimir el tar.gz
  "curl -L $FILES_TAR_URL -o web/sites/default/files.tar.gz",
  "tar -xzf web/sites/default/files.tar.gz -C web/sites/default/",
  "rm web/sites/default/files.tar.gz",

  # Instalar dependencias
  "composer install --no-dev --optimize-autoloader",

  # Reconstruir caché
  "./vendor/bin/drush cr"
]

[start]
# Aquí es donde realmente migramos los archivos en cada despliegue
cmd = "php -S 0.0.0.0:$PORT -t web"
