[env]
COMPOSER_ALLOW_SUPERUSER = "1"
COMPOSER_ALLOW_PLUGIN = "true"

[setup]
packages = [
  "php8.2",
  "composer",
  "php8.2-mysql",
  "php8.2-mbstring",
  "php8.2-gd",
  "php8.2-dom",
  "php8.2-session",
  "php8.2-simplexml",
  "php8.2-filter",
  "php8.2-bcmath",
  "curl",
  "tar"
]

[build]
commands = [
  "rm -rf web/sites/default/files",
  "mkdir -p web/sites/default",
  "chmod -R 777 web/sites/default/",
  "curl -L $FILES_TAR_URL -o web/sites/default/files.tar.gz",
  "tar -xzf web/sites/default/files.tar.gz -C web/sites/default/",
  "rm web/sites/default/files.tar.gz",
  "COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader",
  "COMPOSER_ALLOW_SUPERUSER=1 composer drupal:scaffold",
  "ls -la web | grep core",
  "ls web/modules/contrib",
  "php vendor/bin/drush cr",
  "php vendor/bin/drush cache:rebuild"
]

[start]
command = "php -S 0.0.0.0:$PORT -t web"