[setup]
# Paquetes del sistema necesarios
packages = [
  "php8.2",
  "composer",
  "php8.2-mysql",
  "php8.2-mbstring",
  "php8.2-gd",
  "php8.2-dom",
  "php8.2-session",
  "php8.2-simplexml",
  "php8.2-filter",
  "php8.2-bcmath",
  "curl",
  "tar"
]

[build]
commands = [
  # Limpiar archivos previos
  "rm -rf web/sites/default/files",
  "mkdir -p web/sites/default",
  "chmod -R 777 web/sites/default/",

  # Descargar y descomprimir los archivos
  "curl -L $FILES_TAR_URL -o web/sites/default/files.tar.gz",
  "tar -xzf web/sites/default/files.tar.gz -C web/sites/default/",
  "rm web/sites/default/files.tar.gz",

  # Instalar dependencias de Composer (con permisos elevados)
  "COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader",

  # Reconstruir el core y limpiar cachés de Drupal
  "COMPOSER_ALLOW_SUPERUSER=1 composer drupal:scaffold",
  "ls -la web | grep core",
  "ls web/modules/contrib",
  "php vendor/bin/drush cr",
  "php vendor/bin/drush cache:rebuild"
]

[start]
# Servir el sitio Drupal
command = "php -S 0.0.0.0:$PORT -t web"